export const weatherCodeMap: Record<number, string> = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Light drizzle",
  53: "Moderate drizzle",
  55: "Dense drizzle",
  56: "Light freezing drizzle",
  57: "Dense freezing drizzle",
  61: "Slight rain",
  63: "Moderate rain",
  65: "Heavy rain",
  66: "Light freezing rain",
  67: "Heavy freezing rain",
  71: "Slight snow fall",
  73: "Moderate snow fall",
  75: "Heavy snow fall",
  77: "Snow grains",
  80: "Slight rain showers",
  81: "Moderate rain showers",
  82: "Violent rain showers",
  85: "Slight snow showers",
  86: "Heavy snow showers",
  95: "Thunderstorm",
  96: "Thunderstorm with slight hail",
  99: "Thunderstorm with heavy hail",
};

export const weatherIconMap: Record<number, string> = {
  0: "☀️",
  1: "🌤️",
  2: "⛅",
  3: "☁️",
  45: "🌫️",
  48: "🌫️",
  51: "🌧️",
  53: "🌧️",
  55: "🌧️",
  56: "🌧️",
  57: "🌧️",
  61: "🌧️",
  63: "🌧️",
  65: "🌧️",
  66: "🌧️",
  67: "🌧️",
  71: "❄️",
  73: "❄️",
  75: "❄️",
  77: "❄️",
  80: "🌧️",
  81: "🌧️",
  82: "🌧️",
  85: "❄️",
  86: "❄️",
  95: "⛈️",
  96: "⛈️",
  99: "⛈️",
};

export const THAI_WEATHER_MESSAGES: Record<number, string> = {
  0: "ท้องฟ้าแจ่มใส",
  1: "ท้องฟ้าแจ่มใสเป็นส่วนใหญ่",
  2: "มีเมฆบางส่วน",
  3: "มีเมฆมาก",
  45: "มีหมอก",
  48: "มีหมอก",
  51: "ฝนโปรยเบาๆ",
  53: "ฝนโปรยปานกลาง",
  55: "ฝนโปรยหนัก",
  56: "ฝนโปรยปานกลาง",
  57: "ฝนโปรยหนัก",
  61: "ฝนตกเล็กน้อย",
  63: "ฝนตกปานกลาง",
  65: "ฝนตกหนัก",
  66: "ฝนตกปานกลาง",
  67: "ฝนตกหนัก",
  71: "หิมะตกเล็กน้อย",
  73: "หิมะตกปานกลาง",
  75: "หิมะตกหนัก",
  77: "หิมะตก",
  80: "ฝนตกเป็นระยะๆ",
  81: "ฝนตกเป็นระยะๆ ปานกลาง",
  82: "ฝนตกเป็นระยะๆ หนัก",
  85: "หิมะตกเป็นระยะๆ",
  86: "หิมะตกเป็นระยะๆ หนัก",
  95: "พายุฝนฟ้าคะนอง",
  96: "พายุฝนฟ้าคะนอง",
  99: "พายุฝนฟ้าคะนองหนัก",
};

export const THAI_GENERAL_MESSAGES: Record<string, string> = {
  sunny: "☀️ สดใส เหมาะกับการออกไปทำกิจกรรม",
  partlyCloudy: "⛅ ท้องฟ้ามีเมฆบางส่วน อากาศสบาย",
  overcast: "☁️ มีเมฆมาก เตรียมร่มเผื่อด้วย",
  rain: "🌧️ ฝนกำลังตก พกร่มไปด้วย",
  lightRain: "🌧️ ฝนตกเบาๆ ออกไปได้",
  moderateRain: "🌧️ ฝนตกปานกลาง เตรียมร่ม",
  heavyRain: "🌧️ ฝนตกหนัก พกร่มและเสื้อกันฝน",
  thunderstorm: "⛈️ พายุฝนฟ้าคะนอง หลีกเลี่ยงที่โล่ง",
  fog: "🌫️ มีหมอก ควันวิสัยทัศน์ต่ำ",
  hail: "⛈️ มีลูกเห็บตก ระวังอันตราย",
  snow: "❄️ หิมะกำลังตก แต่งกายให้อบอุ่น",
};

export const DEFAULT_MESSAGE = "อากาศเปลี่ยนแปลงบ่อย ดูแลสุขภาพด้วยนะ 🌦️";

export function weatherLabel(code: number): string {
  return weatherCodeMap[code] ?? `Code ${code}`;
}
