export const SUSPICIOUS_PATTERNS = [
  "powershell -enc",
  "frombase64string",
  "eval(",
  "cmd.exe /c",
  "wget http",
  "curl http",
  "reg add hkcu",
  "startup",
  "createobject",
  "wscript.shell",
  "bitcoin",
  "xmrig",
  "discord webhook",
  "processhacker",
  "mshta",
  "ie4u5tmp",
  "svch0st.exe",
  "explorer.scr",
  "taskhost.exe",
  "rstrui.exe",
  "reg.exe",
  "regsvr32",
  "msiexec.exe",
  "certutil.exe",
  "netsh.exe",
  "bginfo.exe",
  "wmic.exe",
  " PowerShell",
  "winrar",
  "7zip",
  "unknown.exe",
  "Unknown.exe",
  "0.exe",
  "iexplorer.exe",
  "iexplor.exe",
  "conime.exe",
  "conhost.exe",
  "csrss.exe",
  "dwm.exe",
  "lsass.exe",
  "csrss.exe",
  "services.exe",
  "winlogon.exe",
];
